const lang = [
    {//English
        gr6sched: "6<sup>th</sup> grade schedule",
        gr7sched: "7<sup>th</sup> grade schedule",
        gr8sched: "8<sup>th</sup> grade schedule",
        paused: "Paused",
        dark: "Dark Mode",
        light: "Light Mode",
        colors: "COLORS",
        ytest: "Currently Testing",
        ntest: "Not Testing",
        learnt: "Learn't",
        loading: "Loading...",
        ussa: " until school starts again",
        summer: "Summer!",
        dwtd: "% done with the day"
    },
    {//Spanish
        gr6sched: "Programa del 6<sup>o</sup> grado",
        gr7sched: "Programa del 7<sup>o</sup> grado",
        gr8sched: "Programa del 8<sup>o</sup> grado", 
        paused: "Pausado",
        dark: "Modo oscuro",
        light: "Modo claro",
        colors: "COLORES",
        ytest: "Actualmente evaluando",
        ntest: "No evaluando",
        learnt: "No escuela",
        loading: "Cargando...",
        ussa: " hasta la escuela empieza",
        summer: "¡Verano!",
        dwtd: "% del día ha pasado"
    },
    {//French
        gr6sched: "Programme de la 6<sup>e</sup>",
        gr7sched: "Programme de la 5<sup>e</sup>",
        gr8sched: "Programme de la 4<sup>e</sup>",
        paused: "Arrêté",
        dark: "Mode foncé",
        light: "Mode claire",
        colors: "COULEURS",
        ytest: "Actuellement en interrogeant",
        ntest: "Pas en interrogeant",
        learnt: "Pas de l'école",
        loading: "En chargeant...",
        ussa: " jusqu'à ce que l'école commence",
        summer: "Été !",
        dwtd: " % du jour a passé"
    }
]